name: txconnect
description: An Unoffical API for txConnect SCUC.
version: 1.0.3
homepage: https://github.com/Clemens-CAS/txconnect-api

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  html: ^0.14.0+3
  http: ^0.12.1

  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
